name: CI
env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xms6G -Xmx6G -Xss4M -XX:+UseG1GC
on:
  pull_request:
  push:
    branches: ['main']
  release:
    types:
      - published
      - edited
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Restore cache
        uses: coursier/cache-action@v6
        id: coursier-cache
      - name: Setup Scala, JDK
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: Fetch dependencies
        if: steps.coursier-cache.outputs.cache-hit-sbt-ivy2-cache != 'true'
        run: sbt +update
      - name: Lint code
        run: sbt lint
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        java: ['temurin:11', 'temurin:17', 'temurin:21']
        scala: ['2.12.21', '2.13.16', '3.3.7']
        platform: ['JVM', 'Native', 'JS']
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Restore cache
        uses: coursier/cache-action@v6
        id: coursier-cache
      - name: Setup Scala, JDK
        uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: ${{ matrix.java }}
      - name: Fetch dependencies
        if: steps.coursier-cache.outputs.cache-hit-sbt-ivy2-cache != 'true'
        run: sbt +update
      - name: Run tests
        run: sbt ++${{ matrix.scala }}! test${{ matrix.platform }}
  mima_check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 300
      - name: Fetch tags
        run: git fetch --depth=300 origin +refs/tags/*:refs/tags/*
      - name: Restore cache
        uses: coursier/cache-action@v6
        id: coursier-cache
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:21
          apps: sbt
      - name: Fetch dependencies
        if: steps.coursier-cache.outputs.cache-hit-sbt-ivy2-cache != 'true'
        run: sbt +update
      - name: Check binary compatibility
        run: sbt +mimaReportBinaryIssues
  ci:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - run: echo "All checks passed"
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    needs: [lint, build, mima_check]
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Scala, JDK
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: Run release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
